"""Beautiful Executive MIS PDF Report Builder.

Renders a multi-section PDF with embedded matplotlib charts and professional styling.
Uses reportlab for layout/tables and matplotlib for chart rendering.

Sub-modules:
  pdf_styles  — colours, constants, flowables, table helpers
  pdf_charts  — matplotlib chart renderers
  pdf_sections — section builders (cover, exec summary, emissions, EWW, etc.)
"""
import io
from datetime import datetime, timezone
from typing import Any, Dict

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate

# ─── Re-export everything sub-modules need ────────────────────────────────────
from .pdf_styles import (                                       # noqa: F401
    BRAND, BRAND_LIGHT, BRAND_ACCENT, DARK, TEXT_PRIMARY, TEXT_SECONDARY,
    TEXT_MUTED, TABLE_HEADER_BG, TABLE_ALT_ROW, BORDER_COLOR, RED_TEXT,
    GREEN_TEXT, SCOPE_COLORS, SCOPE_LABELS, EA_COLORS,
    SCOPE1_CAT_COLORS, SCOPE2_CAT_COLORS, BIOGENIC_CAT_COLORS,
    SCOPE3_SHADES, SECTION_COLORS, INSIGHT_COLORS,
    ProgressBarFlowable, SectionHeader, ColoredSectionBar, KPICard,
    _styled_table, _insight_para, _fmt_val, _exec_summary_section_table,
)
from .pdf_charts import (                                       # noqa: F401
    _render_donut_chart, _render_trend_chart, _render_rolling_trend,
    _render_resource_fy_trend, _render_target_comparison,
    _render_facility_bar_chart, _render_labeled_trend,
    _render_deep_donut, _render_multiline_trend, _render_grouped_bar,
)
from .pdf_sections import (                                     # noqa: F401
    _sec_cover, _sec_executive_summary, _sec_emissions_analytics,
    _sec_facility_performance, _sec_energy_performance,
    _sec_water_performance, _sec_waste_performance,
    _sec_incidents_compliance, _sec_supplier_assessment, _sec_targets,
)


# ─── Page Callbacks ──────────────────────────────────────────────────────────

def _draw_cover_bg(canvas_obj, doc):
    c = canvas_obj
    w, h = A4
    c.setFillColor(colors.HexColor(BRAND))
    c.rect(0, h - 8, w, 8, fill=1, stroke=0)
    c.rect(0, 0, w, 4, fill=1, stroke=0)
    c.rect(0, 0, 4, h, fill=1, stroke=0)
    c.setFillColor(colors.HexColor(BRAND_LIGHT))
    c.circle(w - 50, h - 50, 130, fill=1, stroke=0)
    c.setFillColor(colors.HexColor("#bbf7d0"))
    c.circle(w - 30, h - 80, 65, fill=1, stroke=0)


def _draw_content_page(canvas_obj, doc):
    c = canvas_obj
    w, h = A4
    c.setStrokeColor(colors.HexColor(BRAND))
    c.setLineWidth(1.5)
    c.line(36, h - 28, w - 36, h - 28)
    c.setFont("Helvetica", 7)
    c.setFillColor(colors.HexColor(TEXT_MUTED))
    c.drawString(36, h - 24, "SustainRepo ESG MIS Report")
    c.drawRightString(w - 36, h - 24, f"Page {doc.page}")
    c.setStrokeColor(colors.HexColor(BORDER_COLOR))
    c.setLineWidth(0.5)
    c.line(36, 30, w - 36, 30)
    c.setFont("Helvetica", 6)
    c.setFillColor(colors.HexColor(TEXT_MUTED))
    c.drawString(36, 20, "Confidential  |  Generated by SustainRepo")
    c.drawRightString(w - 36, 20, datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))


# ─── Main Entry Point ────────────────────────────────────────────────────────

def build_beautiful_executive_pdf(report: Dict[str, Any], organization_name: str, generated_by: str) -> bytes:
    """Generate the complete multi-section executive MIS PDF report."""
    buffer = io.BytesIO()
    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=36, leftMargin=36,
                            topMargin=42, bottomMargin=42)
    story: list = []

    filters = report.get("filters", {})
    period_start = filters.get("reporting_period_start", "---")
    period_end = filters.get("reporting_period_end", "---")

    selected = set(report.get("selected_sections") or [])
    include_all = not selected
    include_ghg = include_all or "ghg" in selected
    include_resources = include_all or bool(selected & {"energy", "water", "waste"})
    include_targets = include_all or bool(selected & {"voluntary_environment", "voluntary_social", "voluntary_governance", "sbti"})

    _sec_cover(story, styles, organization_name, period_start, period_end, generated_by, report.get("reporting_context"))
    _sec_executive_summary(story, styles, report)
    if include_ghg:
        _sec_emissions_analytics(story, styles, report)
        _sec_facility_performance(story, styles, report)
    if include_resources:
        _sec_energy_performance(story, styles, report)
        _sec_water_performance(story, styles, report)
        _sec_waste_performance(story, styles, report)
    if include_all or "social" in selected or "governance" in selected:
        _sec_incidents_compliance(story, styles, report)
        _sec_supplier_assessment(story, styles, report)
    if include_targets:
        _sec_targets(story, styles, report)

    doc.build(story, onFirstPage=_draw_cover_bg, onLaterPages=_draw_content_page)
    return buffer.getvalue()
