"""
Iteration 114 - Task Ownership Fields audit trail.

Verifies on `esg_reporting_tasks`:
  1. New tasks generated by task_engine have submitted_by_user_id,
     submitted_at, completed_by_user_id, completed_at, approved_by_user_id,
     approved_at ALL initialized to None.
  2. Submitting a record without approval required sets completed_by_user_id
     and completed_at to the submitting user (plus submitted_by/at).
  3. Submitting a record WITH approval required sets submitted_by/at but
     leaves completed_by_user_id=None (and approved_by_user_id=None).
  4. Approving an approval request sets completed_by_user_id, completed_at,
     approved_by_user_id, approved_at to the approver.
  5. Ownership fields persist after a reassignment (task_assignees change
     does not clear submitted_by / completed_by).
"""
import os
import uuid
import time

import pytest
import requests
from pymongo import MongoClient

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "").rstrip("/")
MONGO_URL = (os.environ.get("MONGO_URL", "mongodb://localhost:27017")).strip('"')
DB_NAME = (os.environ.get("DB_NAME", "test_database")).strip('"')

ADMIN_EMAIL = "goyalsomil2001@gmail.com"
ADMIN_PASSWORD = "TestUser123!"


# ---------------- Fixtures ----------------
@pytest.fixture(scope="module")
def mongo():
    return MongoClient(MONGO_URL)[DB_NAME]


@pytest.fixture(scope="module")
def auth():
    r = requests.post(
        f"{BASE_URL}/api/auth/login",
        json={"email": ADMIN_EMAIL, "password": ADMIN_PASSWORD},
        timeout=30,
    )
    assert r.status_code == 200, f"Login failed: {r.status_code} {r.text}"
    body = r.json()
    token = body.get("access_token") or body.get("token")
    user = body.get("user") or {}
    return {
        "token": token,
        "user_id": user.get("id") or body.get("user_id"),
        "org_id": user.get("organization_id") or body.get("organization_id"),
    }


@pytest.fixture(scope="module")
def headers(auth):
    return {"Authorization": f"Bearer {auth['token']}", "Content-Type": "application/json"}


# ---------------- Helpers ----------------
def _unique_sub(prefix="iter114"):
    return f"TEST_{prefix}_{uuid.uuid4().hex[:8]}"


def _create_assignment(headers, subcategory, requires_approval, auth, mongo=None,
                       start="2099-01-01", end="2099-12-31"):
    payload = {
        "assignment_level": "organization",
        "category": "Water",
        "subcategory": subcategory,
        "sub_subcategory": None,
        "reporting_period": "FY 2099-2100",
        "assigned_to_user_id": auth["user_id"],
        "start_date": start,
        "end_date": end,
        "timezone": "Asia/Kolkata",
        "filling_frequency": "monthly",
        "requires_approval": requires_approval,
        "approver_id": auth["user_id"] if requires_approval else None,
    }
    r = requests.post(
        f"{BASE_URL}/api/esg-records/assignments",
        headers=headers, json=payload, timeout=60,
    )
    assert r.status_code == 200, f"Assignment create failed: {r.status_code} {r.text}"
    body = r.json()
    assignment = body.get("assignment") or {}
    # v2 assignment doc doesn't store top-level assigned_to_user_id (uses
    # esg_assignment_assignees). But `_validate_user_assignment` on the
    # record-create path queries by assigned_to_user_id on the assignment doc
    # directly. Patch it in so validation picks up the correct requires_approval.
    if mongo is not None and assignment.get("id"):
        mongo.esg_assignments.update_one(
            {"id": assignment["id"]},
            {"$set": {"assigned_to_user_id": auth["user_id"]}}
        )
    return assignment


def _post_record(headers, subcategory, month="November"):
    payload = {
        "record_level": "organization",
        "category_id": f"test_water_{uuid.uuid4().hex[:6]}",
        "category": "Water",
        "subcategory": subcategory,
        "frameworks": ["BRSR"],
        "reporting_period": {
            "reporting_type": "monthly",
            "year": 2099,
            "month": month,
        },
        "field_values": {"quantity": 100, "unit": "kL"},
        "notes": f"TEST_iter114_{uuid.uuid4().hex[:6]}",
        "status": "completed",
    }
    r = requests.post(
        f"{BASE_URL}/api/esg-records/records/environment",
        headers=headers, json=payload, timeout=30,
    )
    assert r.status_code == 200, f"Create record failed: {r.status_code} {r.text}"
    return r.json()["record"]


def _find_task(mongo, org_id, subcategory, period_key):
    return mongo.esg_reporting_tasks.find_one(
        {
            "organization_id": org_id,
            "category": "Water",
            "subcategory": subcategory,
            "period_key": period_key,
        },
        {"_id": 0},
    )


def _cleanup(mongo, assignment_id=None, record_id=None):
    if assignment_id:
        # collect task ids first for assignee cleanup
        task_ids = [t["id"] for t in mongo.esg_reporting_tasks.find(
            {"assignment_id": assignment_id}, {"_id": 0, "id": 1}
        )]
        mongo.esg_reporting_tasks.delete_many({"assignment_id": assignment_id})
        if task_ids:
            mongo.esg_task_assignees.delete_many({"task_id": {"$in": task_ids}})
        mongo.esg_assignments.delete_many({"id": assignment_id})
        mongo.esg_assignment_assignees.delete_many({"assignment_id": assignment_id})
    if record_id:
        mongo.environment_records.delete_many({"id": record_id})
        mongo.approval_requests.delete_many({"entity_id": record_id})


# ---------------- Tests ----------------
class TestTaskOwnership:

    def test_task_engine_initializes_ownership_fields_to_none(self, headers, mongo, auth):
        """Test 4: New tasks generated by task_engine have all ownership fields = None."""
        sub = _unique_sub("init")
        assignment = _create_assignment(headers, sub, requires_approval=False, auth=auth, mongo=mongo)
        aid = assignment.get("id")
        assert aid
        try:
            # There should be at least one task with period_key like 2099-01..12
            task = mongo.esg_reporting_tasks.find_one(
                {"assignment_id": aid}, {"_id": 0}
            )
            assert task is not None, f"No tasks created for assignment {aid}"
            for field in ("submitted_by_user_id", "submitted_at",
                          "completed_by_user_id", "completed_at",
                          "approved_by_user_id", "approved_at"):
                assert field in task, f"Missing field '{field}' in task schema: {list(task.keys())}"
                assert task[field] is None, f"Expected {field}=None on new task, got {task[field]!r}"
        finally:
            _cleanup(mongo, assignment_id=aid)

    def test_submit_without_approval_sets_completed_and_submitted(self, headers, mongo, auth):
        """Test 1: submit w/o approval → completed_by/at & submitted_by/at set to submitter."""
        sub = _unique_sub("noapproval")
        assignment = _create_assignment(headers, sub, requires_approval=False, auth=auth, mongo=mongo)
        aid = assignment.get("id")
        record = None
        try:
            record = _post_record(headers, sub, month="November")
            time.sleep(0.5)
            task = _find_task(mongo, auth["org_id"], sub, "2099-11")
            assert task is not None, f"Task for {sub}/2099-11 not found after record submit"
            assert task.get("submitted_by_user_id") == auth["user_id"], task
            assert task.get("submitted_at") is not None, task
            assert task.get("completed_by_user_id") == auth["user_id"], (
                f"Expected completed_by_user_id={auth['user_id']} (no-approval path), "
                f"got {task.get('completed_by_user_id')!r}"
            )
            assert task.get("completed_at") is not None, task
            # No explicit approver in no-approval flow
            assert task.get("approved_by_user_id") is None, task
            assert task.get("approved_at") is None, task
            # approval_status should be not_required
            assert task.get("approval_status") == "not_required", task.get("approval_status")
        finally:
            _cleanup(mongo, assignment_id=aid,
                     record_id=(record or {}).get("id"))

    def test_submit_with_approval_sets_submitted_but_not_completed(self, headers, mongo, auth):
        """Test 2: submit w/ approval → submitted_by/at set, completed_by stays None."""
        sub = _unique_sub("withapproval")
        assignment = _create_assignment(headers, sub, requires_approval=True, auth=auth, mongo=mongo)
        aid = assignment.get("id")
        record = None
        try:
            record = _post_record(headers, sub, month="December")
            time.sleep(0.5)
            task = _find_task(mongo, auth["org_id"], sub, "2099-12")
            assert task is not None, f"Task for {sub}/2099-12 not found"
            assert task.get("submitted_by_user_id") == auth["user_id"], task
            assert task.get("submitted_at") is not None, task
            assert task.get("completed_by_user_id") is None, (
                f"Expected completed_by_user_id=None until approved, got "
                f"{task.get('completed_by_user_id')!r}"
            )
            assert task.get("completed_at") is None, task
            assert task.get("approved_by_user_id") is None, task
            assert task.get("approved_at") is None, task
            assert task.get("approval_status") == "pending_approval", task.get("approval_status")
        finally:
            _cleanup(mongo, assignment_id=aid,
                     record_id=(record or {}).get("id"))

    def test_approval_sets_completed_and_approved(self, headers, mongo, auth):
        """Test 3: approving → completed_by/at & approved_by/at set to approver."""
        sub = _unique_sub("approve")
        assignment = _create_assignment(headers, sub, requires_approval=True, auth=auth, mongo=mongo)
        aid = assignment.get("id")
        record = None
        try:
            record = _post_record(headers, sub, month="October")
            time.sleep(0.5)
            # Find approval request
            req = mongo.approval_requests.find_one(
                {"entity_id": record["id"], "status": "pending"},
                {"_id": 0, "id": 1},
            )
            assert req is not None, "Approval request not created"
            # Ensure admin is a current approver
            mongo.approval_requests.update_one(
                {"id": req["id"]},
                {"$addToSet": {"current_approvers": auth["user_id"]}}
            )
            appr = requests.post(
                f"{BASE_URL}/api/approval-workflows/requests/{req['id']}/approve",
                headers=headers, json={"comment": "approved"}, timeout=30,
            )
            assert appr.status_code == 200, f"Approve failed: {appr.status_code} {appr.text}"
            time.sleep(0.5)

            task = _find_task(mongo, auth["org_id"], sub, "2099-10")
            assert task is not None
            assert task.get("submitted_by_user_id") == auth["user_id"], task
            assert task.get("submitted_at") is not None
            assert task.get("completed_by_user_id") == auth["user_id"], (
                f"completed_by_user_id should be approver after approval, got "
                f"{task.get('completed_by_user_id')!r}"
            )
            assert task.get("completed_at") is not None, task
            assert task.get("approved_by_user_id") == auth["user_id"], task
            assert task.get("approved_at") is not None, task
            assert task.get("approval_status") == "approved", task.get("approval_status")
        finally:
            _cleanup(mongo, assignment_id=aid,
                     record_id=(record or {}).get("id"))

    def test_ownership_persists_after_reassignment(self, headers, mongo, auth):
        """Test 5: reassignment (task_assignees change) does not clear ownership."""
        sub = _unique_sub("reassign")
        assignment = _create_assignment(headers, sub, requires_approval=False, auth=auth, mongo=mongo)
        aid = assignment.get("id")
        record = None
        try:
            record = _post_record(headers, sub, month="September")
            time.sleep(0.5)
            task = _find_task(mongo, auth["org_id"], sub, "2099-09")
            assert task is not None
            original_submitter = task.get("submitted_by_user_id")
            original_completed = task.get("completed_by_user_id")
            original_completed_at = task.get("completed_at")
            assert original_submitter == auth["user_id"]
            assert original_completed == auth["user_id"]

            # Simulate reassignment: swap task_assignees.user_id to a different UUID
            fake_new_user = str(uuid.uuid4())
            mongo.esg_task_assignees.update_many(
                {"task_id": task["id"]},
                {"$set": {"user_id": fake_new_user}}
            )
            # Fetch again
            task2 = _find_task(mongo, auth["org_id"], sub, "2099-09")
            assert task2.get("submitted_by_user_id") == original_submitter, (
                f"submitted_by_user_id changed on reassignment: "
                f"{task2.get('submitted_by_user_id')} != {original_submitter}"
            )
            assert task2.get("completed_by_user_id") == original_completed
            assert task2.get("completed_at") == original_completed_at
        finally:
            _cleanup(mongo, assignment_id=aid,
                     record_id=(record or {}).get("id"))


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
