import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { FileText, ListChecks, ShieldCheck, Trash2, Upload } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';
import { useSupplierAssessmentPeriod } from '../../contexts/SupplierAssessmentPeriodContext';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '../../components/ui/alert-dialog';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { SupplierAssignmentPicker } from './components/SupplierAssignmentPicker';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

const groupPublishedDocuments = (requirements) => Object.values((requirements || []).reduce((groups, requirement) => {
  const key = requirement.document_version_id || requirement.id;
  const existing = groups[key];
  if (!existing) {
    groups[key] = { ...requirement, supplier_relationship_ids: [...(requirement.supplier_relationship_ids || [])] };
    return groups;
  }
  existing.supplier_relationship_ids = [...new Set([
    ...(existing.supplier_relationship_ids || []),
    ...(requirement.supplier_relationship_ids || []),
  ])];
  return groups;
}, {}));

export default function SupplierDocumentsAdmin() {
  const { getAuthHeader } = useAuth();
  const { reportingPeriod } = useSupplierAssessmentPeriod();
  const [documents, setDocuments] = useState([]); const [selectedSuppliers, setSelectedSuppliers] = useState([]);
  const [title, setTitle] = useState(''); const [file, setFile] = useState(null); const [dueDate, setDueDate] = useState(''); const [responseMode, setResponseMode] = useState('ACCEPTANCE'); const [statusOptions, setStatusOptions] = useState('I have done it\nI will do it\nIt is in progress');
  const [uploading, setUploading] = useState(false); const [pendingDelete, setPendingDelete] = useState(null); const [deletingId, setDeletingId] = useState(''); const [responseDialog, setResponseDialog] = useState(null); const [responseData, setResponseData] = useState(null); const [loadingResponses, setLoadingResponses] = useState(false); const [unlockingSupplierId, setUnlockingSupplierId] = useState('');

  const loadDocuments = useCallback(async () => { try { const documentResponse = await axios.get(`${API}/supplier-assessment/documents?reporting_period=${encodeURIComponent(reportingPeriod)}`, { headers: getAuthHeader() }); setDocuments(groupPublishedDocuments(documentResponse.data)); } catch { toast.error('Could not load agreement requirements'); } }, [getAuthHeader, reportingPeriod]);
  useEffect(() => { loadDocuments(); }, [loadDocuments]);

  const uploadAgreement = async () => {
    if (!file) { toast.error('Choose an agreement file first'); return; }
    if (!selectedSuppliers.length) { toast.error('Select at least one supplier'); return; }
    const options = statusOptions.split('\n').map((option) => option.trim()).filter(Boolean);
    if (responseMode === 'STATUS' && !options.length) { toast.error('Add at least one status option'); return; }
    const data = new FormData(); data.append('file', file); data.append('title', title); data.append('due_date', dueDate); data.append('response_mode', responseMode); data.append('response_options_json', JSON.stringify(options)); data.append('supplier_relationship_ids', JSON.stringify(selectedSuppliers)); setUploading(true);
    try { await axios.post(`${API}/supplier-assessment/documents`, data, { headers: getAuthHeader() }); toast.success('Agreement published to selected suppliers'); setTitle(''); setDueDate(''); setFile(null); setSelectedSuppliers([]); document.getElementById('supplier-agreement-file-input').value = ''; await loadDocuments(); } catch (error) { toast.error(error.response?.data?.detail || 'Could not publish agreement'); } finally { setUploading(false); }
  };

  const viewResponses = async (document) => { setResponseDialog(document); setResponseData(null); setLoadingResponses(true); try { setResponseData((await axios.get(`${API}/supplier-assessment/documents/${document.id}/responses`, { headers: getAuthHeader() })).data); } catch (error) { toast.error(error.response?.data?.detail || 'Could not load supplier responses'); } finally { setLoadingResponses(false); } };
  const unlockResponse = async (response) => { if (!responseDialog || !window.confirm(`Unlock ${response.supplier_name}'s response for resubmission?`)) return; setUnlockingSupplierId(response.supplier_relationship_id); try { await axios.post(`${API}/supplier-assessment/suppliers/${response.supplier_relationship_id}/documents/${responseDialog.id}/reopen`, {}, { headers: getAuthHeader() }); toast.success('Document response unlocked'); await viewResponses(responseDialog); } catch (error) { toast.error(error.response?.data?.detail || 'Could not unlock document response'); } finally { setUnlockingSupplierId(''); } };
  const deleteAgreement = async () => { if (!pendingDelete) return; setDeletingId(pendingDelete.id); try { await axios.delete(`${API}/supplier-assessment/documents/${pendingDelete.id}`, { headers: getAuthHeader() }); toast.success('Agreement deleted from supplier access'); setPendingDelete(null); await loadDocuments(); } catch (error) { toast.error(error.response?.data?.detail || 'Could not delete agreement'); } finally { setDeletingId(''); } };

  return <div className="space-y-8" data-testid="supplier-documents-admin-page"><div><h1 className="text-3xl font-semibold text-stone-900">Supplier agreements</h1><p className="mt-2 text-sm text-stone-600">Publish an agreement with the response your selected suppliers must provide.</p></div>
    <Card data-testid="supplier-agreement-upload-card"><CardHeader><CardTitle className="flex items-center gap-2"><Upload className="h-5 w-5 text-emerald-700" />Publish agreement</CardTitle><CardDescription>PDF, DOC, or DOCX up to 10MB.</CardDescription></CardHeader><CardContent className="grid gap-5 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="supplier-agreement-title">Agreement title</Label><Input id="supplier-agreement-title" value={title} onChange={(event) => setTitle(event.target.value)} data-testid="supplier-agreement-title-input" /></div><div className="space-y-2"><Label htmlFor="supplier-agreement-file-input">Agreement file</Label><Input id="supplier-agreement-file-input" type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event) => setFile(event.target.files?.[0] || null)} data-testid="supplier-agreement-file-input" /></div><div className="space-y-2"><Label htmlFor="supplier-agreement-due-date">Due date</Label><Input id="supplier-agreement-due-date" type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} data-testid="supplier-agreement-due-date-input" /></div><div className="space-y-2"><Label htmlFor="supplier-document-response-mode">Response Type</Label><select id="supplier-document-response-mode" value={responseMode} onChange={(event) => setResponseMode(event.target.value)} className="h-10 w-full border border-stone-300 bg-white px-3 text-sm" data-testid="supplier-document-response-mode-select"><option value="ACCEPTANCE">Acceptance</option><option value="STATUS">Status</option></select></div>{responseMode === 'STATUS' && <div className="space-y-2"><Label htmlFor="supplier-document-status-options">Status options</Label><textarea id="supplier-document-status-options" value={statusOptions} onChange={(event) => setStatusOptions(event.target.value)} className="min-h-24 w-full border border-stone-300 p-3 text-sm" data-testid="supplier-document-status-options-input" /></div>}<div className="md:col-span-2"><SupplierAssignmentPicker selectedIds={selectedSuppliers} onChange={setSelectedSuppliers} getAuthHeader={getAuthHeader} testIdPrefix="document" reportingPeriod={reportingPeriod} /></div><div className="md:col-span-2"><Button onClick={uploadAgreement} disabled={uploading} data-testid="publish-supplier-agreement-button">{uploading ? 'Publishing…' : 'Publish agreement'}</Button></div></CardContent></Card>
    <div className="space-y-3" data-testid="published-supplier-agreements-list">{documents.length === 0 ? <p className="py-8 text-center text-sm text-stone-500" data-testid="supplier-agreements-empty-state">No agreements have been published.</p> : documents.map((document) => <Card key={document.id} data-testid={`published-supplier-agreement-${document.id}`}><CardContent className="flex flex-col gap-4 py-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><ShieldCheck className="h-5 w-5 text-emerald-700" /><div><p className="font-medium text-stone-900">{document.title}</p><p className="text-xs text-stone-500">{document.response_mode === 'STATUS' ? `Status: ${(document.response_options || []).join(' · ')}` : 'Acceptance required'} · Assigned to {document.supplier_relationship_ids ? document.supplier_relationship_ids.length : 'all active'} suppliers</p></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => viewResponses(document)} data-testid={`view-document-responses-${document.id}`}><ListChecks className="mr-1 h-4 w-4" />Responses</Button><Button variant="outline" size="sm" disabled={deletingId === document.id} onClick={() => setPendingDelete(document)} data-testid={`delete-supplier-agreement-${document.id}`}><Trash2 className="mr-1 h-4 w-4" />Delete</Button></div></CardContent></Card>)}</div>
    <Dialog open={Boolean(responseDialog)} onOpenChange={(open) => !open && setResponseDialog(null)}><DialogContent className="max-w-3xl" data-testid="document-responses-dialog"><DialogHeader><DialogTitle data-testid="document-responses-dialog-title">Supplier responses — {responseDialog?.title}</DialogTitle></DialogHeader>{loadingResponses ? <p data-testid="document-responses-loading">Loading responses…</p> : <div className="space-y-2" data-testid="document-responses-list">{(responseData?.responses || []).map((response) => <div key={response.supplier_relationship_id} className="flex items-center justify-between gap-4 border-b py-3" data-testid={`document-response-${response.supplier_relationship_id}`}><span className="font-medium">{response.supplier_name}</span><div className="flex items-center gap-3"><span className="text-sm text-stone-600" data-testid={`document-response-value-${response.supplier_relationship_id}`}>{response.submission_status === 'reopened' ? 'Unlocked for resubmission' : response.selected_response || 'No response yet'}</span>{response.can_unlock && response.submission_status !== 'reopened' && <Button variant="outline" size="sm" disabled={unlockingSupplierId === response.supplier_relationship_id} onClick={() => unlockResponse(response)} data-testid={`unlock-document-response-${response.supplier_relationship_id}`}>{unlockingSupplierId === response.supplier_relationship_id ? 'Unlocking…' : 'Unlock'}</Button>}</div></div>)}</div>}</DialogContent></Dialog>
    <AlertDialog open={Boolean(pendingDelete)} onOpenChange={(open) => !open && setPendingDelete(null)}><AlertDialogContent data-testid="delete-supplier-agreement-dialog"><AlertDialogHeader><AlertDialogTitle>Delete {pendingDelete?.title}?</AlertDialogTitle><AlertDialogDescription>This removes the agreement from all active supplier assignments. Its historical response record and stored file are retained for audit purposes.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel data-testid="cancel-delete-supplier-agreement-button">Cancel</AlertDialogCancel><AlertDialogAction onClick={deleteAgreement} data-testid="confirm-delete-supplier-agreement-button">Delete agreement</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}