import React, { useCallback, useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { ArrowRight, Lock, Send } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '../../components/ui/alert-dialog';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/table';
import { SupplierDataVerificationAcknowledgement } from './components/SupplierDataVerificationAcknowledgement';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

export default function SupplierGHGSubmission() {
  const { getAuthHeader } = useAuth(); const navigate = useNavigate(); const [state, setState] = useState(null); const [submitting, setSubmitting] = useState(false); const [confirmOpen, setConfirmOpen] = useState(false); const [verificationAccepted, setVerificationAccepted] = useState(false);
  const load = useCallback(async () => { try { setState((await axios.get(`${API}/supplier-assessment/my-assessment/emissions/submission`, { headers: getAuthHeader() })).data); } catch (error) { toast.error(error.response?.data?.detail || 'Could not load GHG submission'); } }, [getAuthHeader]);
  useEffect(() => { load(); }, [load]);
  const totals = useMemo(() => (state?.draft_aggregation || []).reduce((all, row) => ({ ...all, [row.scope]: (all[row.scope] || 0) + row.total_emissions }), {}), [state]);
  const lastSubmittedTotals = useMemo(() => (state?.last_submitted_aggregation || []).reduce((all, row) => ({ ...all, [row.scope]: (all[row.scope] || 0) + row.total_emissions }), {}), [state]);
  const submit = async () => { if (!verificationAccepted) return; setSubmitting(true); try { await axios.post(`${API}/supplier-assessment/my-assessment/emissions/submit`, { data_verified: true }, { headers: getAuthHeader() }); toast.success('GHG submission sent'); setConfirmOpen(false); setVerificationAccepted(false); await load(); } catch (error) { toast.error(error.response?.data?.detail || 'Could not submit GHG data'); } finally { setSubmitting(false); } };
  const locked = state?.submission?.status === 'submitted';
  const reopened = state?.submission?.status === 'reopened';
  return <div className="space-y-6" data-testid="supplier-ghg-submission-page"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">Supplier Assessment GHG</h1><p className="mt-2 text-sm text-stone-600">Review your logged GHG data before submitting it to your customer.</p></div>{locked ? <Badge className="bg-stone-200 text-stone-700" data-testid="supplier-ghg-submission-locked"><Lock className="mr-1 h-3 w-3" />Submitted and locked</Badge> : reopened ? <Badge className="bg-amber-100 text-amber-800" data-testid="supplier-ghg-submission-reopened">Unlocked for resubmission</Badge> : null}{!locked && <Button disabled={!state?.can_submit || submitting} onClick={() => setConfirmOpen(true)} data-testid="submit-supplier-ghg-button"><Send className="mr-2 h-4 w-4" />{reopened ? 'Resubmit GHG data' : 'Submit GHG data'}</Button>}</div>
    <div className="grid gap-4 md:grid-cols-2"><Card data-testid="supplier-ghg-scope1-total"><CardContent className="pt-6"><p className="text-sm text-stone-500">Scope 1 draft total</p><p className="mt-1 text-2xl font-semibold">{(totals.scope1 || 0).toFixed(2)} tCO₂e</p><p className="mt-1 text-xs text-stone-500" data-testid="supplier-ghg-last-submitted-scope1">Last submitted: {lastSubmittedTotals.scope1 != null ? `${lastSubmittedTotals.scope1.toFixed(2)} tCO₂e` : '—'}</p></CardContent></Card><Card data-testid="supplier-ghg-scope2-total"><CardContent className="pt-6"><p className="text-sm text-stone-500">Scope 2 draft total</p><p className="mt-1 text-2xl font-semibold">{(totals.scope2 || 0).toFixed(2)} tCO₂e</p><p className="mt-1 text-xs text-stone-500" data-testid="supplier-ghg-last-submitted-scope2">Last submitted: {lastSubmittedTotals.scope2 != null ? `${lastSubmittedTotals.scope2.toFixed(2)} tCO₂e` : '—'}</p></CardContent></Card></div>
    <Card data-testid="supplier-ghg-submission-aggregation"><CardHeader><CardTitle>Scope and category summary</CardTitle></CardHeader><CardContent>{!state ? <p data-testid="supplier-ghg-submission-loading">Loading…</p> : (state.draft_aggregation || []).length === 0 ? locked ? <div className="space-y-3" data-testid="supplier-ghg-submission-locked-empty"><p className="text-sm text-stone-600" data-testid="supplier-ghg-locked-message">Your submitted GHG data is locked. Ask {state.customer_name || 'your customer'} to unlock it before entering or editing values.</p></div> : <div className="flex flex-wrap items-center justify-between gap-3" data-testid="supplier-ghg-submission-empty"><p className="text-sm text-stone-500">No unsubmitted GHG entries are available.</p><Button variant="outline" onClick={() => navigate('/ghg')} data-testid="supplier-ghg-add-data-button">Add GHG data<ArrowRight className="ml-2 h-4 w-4" /></Button></div> : <Table data-testid="supplier-ghg-submission-table"><TableHeader><TableRow><TableHead>Scope</TableHead><TableHead>Category</TableHead><TableHead className="text-right">Entries</TableHead><TableHead className="text-right">Emissions (tCO₂e)</TableHead></TableRow></TableHeader><TableBody>{state.draft_aggregation.map((row) => <TableRow key={`${row.scope}-${row.category}`} data-testid={`supplier-ghg-submission-row-${row.scope}-${row.category}`}><TableCell>{row.scope === 'scope1' ? 'Scope 1' : 'Scope 2'}</TableCell><TableCell>{row.category}</TableCell><TableCell className="text-right">{row.entry_count}</TableCell><TableCell className="text-right font-mono">{row.total_emissions.toFixed(4)}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>
    <AlertDialog open={confirmOpen} onOpenChange={(open) => { setConfirmOpen(open); if (!open) setVerificationAccepted(false); }}><AlertDialogContent data-testid="confirm-supplier-ghg-submit-dialog"><AlertDialogHeader><AlertDialogTitle>{reopened ? 'Resubmit GHG data?' : 'Submit GHG data?'}</AlertDialogTitle><AlertDialogDescription>{reopened ? 'This replaces the parent-visible submission with your revised draft.' : 'This sends the current GHG snapshot to your customer. It becomes locked until your customer unlocks it for resubmission.'}</AlertDialogDescription></AlertDialogHeader><SupplierDataVerificationAcknowledgement checked={verificationAccepted} onCheckedChange={setVerificationAccepted} testIdPrefix="supplier-ghg-data-verification" /><AlertDialogFooter><AlertDialogCancel data-testid="cancel-supplier-ghg-submit-button">Cancel</AlertDialogCancel><AlertDialogAction disabled={submitting || !verificationAccepted} onClick={submit} data-testid="confirm-supplier-ghg-submit-button">{submitting ? 'Submitting…' : reopened ? 'Resubmit GHG data' : 'Submit GHG data'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}