import React from 'react';
import { ArrowRight, Building2, Leaf, Users } from 'lucide-react';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { Button } from '../../../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../../../components/ui/card';
import { SupplierEsgScoreComparison } from '../SupplierEsgScoreComparison';
import { hasValue, scoreText } from './rankingUtils';
import { EsgPerformanceComparison } from './EsgPerformanceComparison';

const summaryScoreTone = (value) => {
  if (!hasValue(value)) return 'bg-stone-100 text-stone-500';
  if (Number(value) >= 80) return 'bg-emerald-50 text-emerald-800';
  if (Number(value) >= 60) return 'bg-amber-50 text-amber-800';
  return 'bg-rose-50 text-rose-800';
};

const EsgScoreBreakdown = ({ averages }) => {
  const dimensions = [{ key: 'environment', label: 'Environment', Icon: Leaf, icon: 'bg-emerald-50 text-emerald-700', bar: 'bg-emerald-600' }, { key: 'social', label: 'Social', Icon: Users, icon: 'bg-blue-50 text-blue-700', bar: 'bg-blue-500' }, { key: 'governance', label: 'Governance', Icon: Building2, icon: 'bg-violet-50 text-violet-700', bar: 'bg-violet-600' }];
  return <Card className="rounded-lg border-stone-200 bg-white shadow-none" data-testid="esg-score-breakdown-card"><CardHeader className="border-b border-stone-100 pb-4"><CardTitle className="text-base text-stone-900">ESG score breakdown <span className="font-normal text-stone-500">(average)</span></CardTitle><div className="mt-4 flex items-end gap-1"><span className="text-4xl font-semibold text-stone-950" data-testid="esg-score-breakdown-overall-score">{scoreText(averages?.esg)}</span><span className="pb-1 text-sm text-stone-500">/100</span></div><p className="mt-1 text-xs text-stone-500">Across submitted assessments</p></CardHeader><CardContent className="space-y-5 pt-5">{dimensions.map(({ key, label, Icon, icon, bar }) => { const value = averages?.[key]; const width = hasValue(value) ? Math.min(100, Math.max(0, Number(value))) : 0; return <div key={key} data-testid={`esg-score-breakdown-${key}`}><div className="mb-2 flex items-center gap-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${icon}`}><Icon className="h-4 w-4" aria-hidden="true" /></span><span className="flex-1 text-sm font-medium text-stone-700">{label}</span><span className="text-sm font-semibold text-stone-950" data-testid={`esg-score-breakdown-${key}-value`}>{scoreText(value)}<span className="ml-0.5 text-xs font-normal text-stone-500">/100</span></span></div><div className="ml-11 h-2 overflow-hidden rounded-full bg-stone-100"><div className={`h-full rounded-full ${bar}`} style={{ width: `${width}%` }} /></div></div>; })}</CardContent></Card>;
};

export const RankingEsgTab = ({ averages, distribution, esg, onViewRankings, overall }) => <section className="space-y-5" data-testid="supplier-ranking-esg-panel">
  <EsgScoreBreakdown averages={averages} />
  <EsgPerformanceComparison averages={averages} suppliers={esg} />
  <section className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card className="rounded-lg border-stone-200 bg-white shadow-none" data-testid="esg-score-distribution-card"><CardHeader className="border-b border-stone-100 pb-4"><CardTitle className="text-base text-stone-900">ESG score distribution <span className="font-normal text-stone-500">(overall scores)</span></CardTitle><p className="mt-1 text-xs text-stone-500">Submitted supplier assessments by score band</p></CardHeader><CardContent className="pt-4">{overall.length ? <div className="grid items-center gap-2 sm:grid-cols-[1fr_auto]"><ResponsiveContainer width="100%" height={206}><PieChart><Pie data={distribution} dataKey="value" nameKey="name" innerRadius={55} outerRadius={83} paddingAngle={3} stroke="none">{distribution.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip formatter={(value) => [`${value} supplier${value === 1 ? '' : 's'}`, '']} /></PieChart></ResponsiveContainer><div className="space-y-2" data-testid="esg-score-distribution-legend">{distribution.map((item) => <div key={item.name} className="flex items-center justify-between gap-5 text-xs"><span className="flex items-center gap-2 text-stone-600"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: item.color }} />{item.name}</span><span className="font-semibold text-stone-900">{item.value}</span></div>)}</div></div> : <p className="py-16 text-center text-sm text-stone-500" data-testid="esg-score-distribution-empty">No submitted ESG assessments yet.</p>}</CardContent></Card><SupplierEsgScoreComparison suppliers={esg} /></section>
  <Card className="rounded-lg border-stone-200 bg-white shadow-none" data-testid="supplier-esg-summary-card"><CardHeader className="flex-row items-center justify-between border-b border-stone-100 pb-4"><div><CardTitle className="text-base text-stone-900">Supplier ESG summary</CardTitle><p className="mt-1 text-xs text-stone-500">Overall and pillar scores for submitted assessments</p></div><Button variant="ghost" size="sm" className="h-8 px-2 text-emerald-800 hover:bg-emerald-50 hover:text-emerald-900" onClick={onViewRankings} data-testid="view-all-esg-summary-button">View rankings <ArrowRight className="ml-1 h-3.5 w-3.5" /></Button></CardHeader><CardContent className="p-0">{esg.length ? <div className="overflow-x-auto"><div className="min-w-[680px] divide-y divide-stone-100"><div className="grid grid-cols-[minmax(12rem,1.8fr)_repeat(4,minmax(5rem,1fr))] gap-3 bg-stone-50 px-5 py-3 text-center text-[11px] font-semibold uppercase tracking-wide text-stone-500"><span>Supplier</span><span>ESG score</span><span>Environment</span><span>Social</span><span>Governance</span></div>{esg.map((row) => <div key={row.supplier_id} className="grid grid-cols-[minmax(12rem,1.8fr)_repeat(4,minmax(5rem,1fr))] items-center gap-3 px-5 py-3.5 text-center" data-testid={`esg-summary-supplier-${row.supplier_id}`}><span className="truncate text-sm font-semibold text-stone-800">{row.company_name}</span><span className={`justify-self-center rounded-full px-2.5 py-1 text-sm font-semibold ${summaryScoreTone(row.esg_score)}`} data-testid={`esg-summary-score-${row.supplier_id}`}>{scoreText(row.esg_score)}</span><span className={`justify-self-center rounded-full px-2.5 py-1 text-sm font-medium ${summaryScoreTone(row.environment_score)}`} data-testid={`esg-summary-environment-score-${row.supplier_id}`}>{scoreText(row.environment_score)}</span><span className={`justify-self-center rounded-full px-2.5 py-1 text-sm font-medium ${summaryScoreTone(row.social_score)}`} data-testid={`esg-summary-social-score-${row.supplier_id}`}>{scoreText(row.social_score)}</span><span className={`justify-self-center rounded-full px-2.5 py-1 text-sm font-medium ${summaryScoreTone(row.governance_score)}`} data-testid={`esg-summary-governance-score-${row.supplier_id}`}>{scoreText(row.governance_score)}</span></div>)}</div></div> : <p className="p-6 text-sm text-stone-500" data-testid="supplier-esg-summary-empty">No submitted ESG assessments yet.</p>}</CardContent></Card>
</section>;