import React from 'react';
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Card, CardContent, CardHeader, CardTitle } from '../../../../components/ui/card';
import { SupplierIntensityComparison } from '../emissions/SupplierIntensityComparison';
import { SupplierMonthlyEmissionsTrend } from '../emissions/SupplierMonthlyEmissionsTrend';
import { SupplierScope1CategoryComparison } from '../emissions/SupplierScope1CategoryComparison';
import { hasValue } from './rankingUtils';

const formatEmissions = (value) => Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 });

export const RankingEmissionsTab = ({ emissions, emissionsAnalytics, reportingPeriod, scopeTotals }) => {
  const metrics = [{ id: 'total', label: 'Total attributed emissions', value: scopeTotals.total, color: 'border-emerald-500' }, { id: 'scope1', label: 'Scope 1 attributed', value: scopeTotals.scope1, color: 'border-emerald-400' }, { id: 'scope2', label: 'Scope 2 attributed', value: scopeTotals.scope2, color: 'border-blue-500' }];
  return <section className="space-y-5" data-testid="supplier-ranking-emissions-panel">
    <section className="grid gap-3 sm:grid-cols-3" aria-label="Supplier emissions summary">{metrics.map((item) => <Card key={item.id} className={`rounded-lg border-stone-200 border-l-4 bg-white shadow-none ${item.color}`} data-testid={`supplier-emissions-${item.id}-metric`}><CardContent className="p-5"><p className="text-xs font-semibold uppercase tracking-wide text-stone-500">{item.label}</p><p className="mt-2 text-3xl font-semibold text-stone-950" data-testid={`supplier-emissions-${item.id}-value`}>{formatEmissions(item.value)}</p><p className="mt-1 text-xs text-stone-500">tCO₂e · {Number(scopeTotals.total) ? `${((Number(item.value) / Number(scopeTotals.total)) * 100).toFixed(1)}% of total` : 'No submitted attributed emissions'}</p></CardContent></Card>)}</section>
    <section className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card className="rounded-lg border-stone-200 bg-white shadow-none" data-testid="supplier-emissions-scope-card"><CardHeader className="border-b border-stone-100 pb-4"><CardTitle className="text-base text-stone-900">Attributed emissions by scope</CardTitle><p className="mt-1 text-xs text-stone-500">Submitted Scope 1 and Scope 2 emissions attributed to your organization</p></CardHeader><CardContent className="pt-4">{Number(scopeTotals.total) ? <ResponsiveContainer width="100%" height={238}><PieChart><Pie data={[{ name: 'Scope 1', value: scopeTotals.scope1 }, { name: 'Scope 2', value: scopeTotals.scope2 }]} dataKey="value" innerRadius={60} outerRadius={88} paddingAngle={3} stroke="none"><Cell fill="#059669" /><Cell fill="#3b82f6" /></Pie><Tooltip formatter={(value) => [`${formatEmissions(value)} tCO₂e`, '']} /><Legend verticalAlign="bottom" iconType="circle" /></PieChart></ResponsiveContainer> : <p className="py-16 text-center text-sm text-stone-500" data-testid="supplier-emissions-scope-empty">No submitted attributed emissions yet.</p>}</CardContent></Card><Card className="rounded-lg border-stone-200 bg-white shadow-none" data-testid="supplier-emissions-comparison-card"><CardHeader className="border-b border-stone-100 pb-4"><CardTitle className="text-base text-stone-900">Supplier attributed emissions comparison</CardTitle><p className="mt-1 text-xs text-stone-500">Submitted emissions attributed to your organization by supplier</p></CardHeader><CardContent className="pt-5">{emissions.length ? <ResponsiveContainer width="100%" height={238}><BarChart data={emissions} barCategoryGap="28%" margin={{ top: 4, right: 8, left: -15, bottom: 0 }}><CartesianGrid vertical={false} stroke="#edece7" /><XAxis dataKey="company_name" tick={{ fontSize: 10, fill: '#78716c' }} interval={0} /><YAxis tick={{ fontSize: 11, fill: '#78716c' }} /><Tooltip formatter={(value) => [`${formatEmissions(value)} tCO₂e`, '']} /><Legend verticalAlign="top" align="right" iconType="circle" wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="total_emissions" name="Attributed emissions" fill="#059669" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer> : <p className="py-16 text-center text-sm text-stone-500" data-testid="supplier-emissions-comparison-empty">No submitted attributed emissions yet.</p>}</CardContent></Card></section>
    <section className="grid gap-5 lg:grid-cols-2" data-testid="supplier-emissions-analytics-grid"><SupplierIntensityComparison data={emissionsAnalytics.intensityData} /><SupplierScope1CategoryComparison data={emissionsAnalytics.scope1CategoryData} categories={emissionsAnalytics.categories} /><div className="lg:col-span-2"><SupplierMonthlyEmissionsTrend data={emissionsAnalytics.monthlyTrend} /></div></section>
    <Card className="rounded-lg border-stone-200 bg-white shadow-none" data-testid="supplier-emissions-summary-card"><CardHeader className="flex-row items-center justify-between border-b border-stone-100 pb-4"><div><CardTitle className="text-base text-stone-900">Supplier attributed emissions summary</CardTitle><p className="mt-1 text-xs text-stone-500">Submitted attributed totals for every reporting supplier</p></div><span className="rounded-full bg-stone-100 px-3 py-1 text-xs font-medium text-stone-600" data-testid="supplier-emissions-summary-period">{reportingPeriod}</span></CardHeader><CardContent className="p-0">{emissions.length ? <div className="overflow-x-auto"><div className="min-w-[700px] divide-y divide-stone-100"><div className="grid grid-cols-[minmax(12rem,1.8fr)_repeat(3,minmax(7rem,1fr))_minmax(7rem,.8fr)] gap-3 bg-stone-50 px-5 py-3 text-[11px] font-semibold uppercase tracking-wide text-stone-500"><span>Supplier</span><span>Scope 1 (tCO2e)</span><span>Scope 2 (tCO2e)</span><span>Total attributed (tCO2e)</span><span>Revenue share</span></div>{emissions.map((row) => { const revenueShare = hasValue(row.revenue_percentage) ? `${Number(row.revenue_percentage).toFixed(1).replace(/\.0$/, '')}%` : '—'; return <div key={row.supplier_id} className="grid grid-cols-[minmax(12rem,1.8fr)_repeat(3,minmax(7rem,1fr))_minmax(7rem,.8fr)] items-center gap-3 px-5 py-3.5" data-testid={`supplier-emissions-summary-${row.supplier_id}`}><span className="truncate text-sm font-semibold text-stone-800">{row.company_name}</span><span className="text-sm text-stone-600">{formatEmissions(row.scope1_emissions)}</span><span className="text-sm text-stone-600">{formatEmissions(row.scope2_emissions)}</span><span className="text-sm font-semibold text-stone-950" data-testid={`supplier-emissions-total-${row.supplier_id}`}>{formatEmissions(row.total_emissions)} tCO₂e</span><span className="text-sm text-stone-600" data-testid={`supplier-revenue-share-${row.supplier_id}`}>{revenueShare}</span></div>; })}</div></div> : <p className="p-6 text-sm text-stone-500" data-testid="supplier-emissions-summary-empty">No submitted attributed emissions yet.</p>}</CardContent></Card>
  </section>;
};