import React from 'react';
import { Factory, FileText, GraduationCap, Leaf } from 'lucide-react';
import { Badge } from '../../../../components/ui/badge';
import { Button } from '../../../../components/ui/button';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../../../components/ui/dialog';
import { hasValue, scoreText } from './rankingUtils';

const formatDate = (value) => (value ? new Date(value).toLocaleDateString() : '—');
const isPastDue = (dueDate) => dueDate && new Date(`${dueDate}T23:59:59`).getTime() < Date.now();
const statusStyle = (status) => (status === 'locked' || status === 'completed' ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : status === 'in_progress' ? 'border-blue-200 bg-blue-50 text-blue-800' : status === 'overdue' ? 'border-rose-200 bg-rose-50 text-rose-800' : 'border-amber-200 bg-amber-50 text-amber-800');

const DetailItem = ({ item, Icon, accent }) => {
  const overdue = !['locked', 'completed', 'submitted'].includes(item.status) && isPastDue(item.due_date);
  const status = overdue ? 'overdue' : item.status;
  const completionContext = item.status === 'locked' ? `Submitted ${formatDate(item.locked_at)}` : item.status === 'completed' ? `Completed ${item.completed_at ? formatDate(item.completed_at) : ''}` : overdue ? `Due ${formatDate(item.due_date)}` : item.status === 'in_progress' ? `${item.progress_percent || 0}% complete` : 'Awaiting supplier response';
  const context = item.due_date && !overdue ? `${completionContext} · Due ${formatDate(item.due_date)}` : completionContext;
  return <div className={`flex items-center justify-between gap-3 border-l-2 ${overdue ? 'border-rose-400 bg-rose-50/50' : accent} px-3 py-2.5`}><div className="flex min-w-0 items-center gap-2"><Icon className="h-4 w-4 shrink-0" /><div className="min-w-0"><p className="truncate text-sm font-medium text-stone-800">{item.name}</p><p className="text-xs text-stone-500">{context}</p></div></div><Badge variant="outline" className={`shrink-0 text-xs ${statusStyle(status)}`} data-testid={`supplier-detail-status-${item.name}`}>{String(status).replace('_', ' ')}</Badge></div>;
};

const DetailSection = ({ accent, empty, Icon, items, title }) => <section><h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-stone-900"><span className={`flex h-7 w-7 items-center justify-center ${accent}`}><Icon className="h-4 w-4" /></span>{title}</h3><div className="space-y-2">{items?.length ? items : <p className="px-1 py-3 text-sm text-stone-500">{empty}</p>}</div></section>;

export const SupplierRankingDetailDialog = ({ detail, onClose, supplier }) => <Dialog open={Boolean(supplier)} onOpenChange={(open) => !open && onClose()}><DialogContent className="max-h-[calc(100dvh-2rem)] max-w-5xl overflow-y-auto" data-testid="ranking-supplier-detail-dialog"><DialogHeader><DialogTitle data-testid="ranking-supplier-detail-title">{supplier?.company_name} — Assessment Detail</DialogTitle><p className="text-sm text-stone-500" data-testid="ranking-supplier-detail-description">Track ESG, GHG, documents and training progress for this supplier.</p></DialogHeader>{!detail ? <p className="py-16 text-center text-sm text-stone-500" data-testid="ranking-supplier-detail-loading">Loading assessment detail…</p> : <><section className="grid gap-3 border-y border-stone-100 py-4 sm:grid-cols-2" data-testid="ranking-supplier-detail-scores"><div className="border-l-4 border-emerald-400 bg-emerald-50/50 p-3"><p className="text-xs text-stone-500">ESG score</p><p className="mt-1 text-2xl font-semibold text-stone-900" data-testid="ranking-supplier-detail-esg-score">{scoreText(supplier?.esg_score)}</p></div><div className="border-l-4 border-amber-400 bg-amber-50/50 p-3"><p className="text-xs text-stone-500">Revenue contribution</p><p className="mt-1 text-2xl font-semibold text-stone-900" data-testid="ranking-supplier-detail-revenue">{hasValue(supplier?.revenue_percentage) ? `${supplier.revenue_percentage}%` : '—'}</p></div></section><section className="grid gap-6 py-3 md:grid-cols-2" data-testid="ranking-supplier-detail-modules"><DetailSection title="ESG" Icon={Leaf} accent="bg-emerald-100 text-emerald-700" empty="No ESG questionnaires assigned." items={(detail.esg_items || []).map((item) => <DetailItem key={item.questionnaire_id} item={item} Icon={Leaf} accent="border-emerald-300" />)} /><DetailSection title="GHG" Icon={Factory} accent="bg-violet-100 text-violet-700" empty="" items={[<DetailItem key="ghg" item={{ ...detail.ghg, name: 'GHG emissions submission' }} Icon={Factory} accent="border-violet-300" />]} /><DetailSection title="Documents" Icon={FileText} accent="bg-sky-100 text-sky-700" empty="No documents assigned." items={(detail.documents || []).map((item) => <DetailItem key={item.id} item={item} Icon={FileText} accent="border-sky-300" />)} /><DetailSection title="Training" Icon={GraduationCap} accent="bg-amber-100 text-amber-700" empty="No training assigned." items={(detail.training || []).map((item) => <DetailItem key={item.id} item={item} Icon={GraduationCap} accent="border-amber-300" />)} /></section></>}<DialogFooter><Button variant="outline" onClick={onClose} data-testid="close-ranking-supplier-detail-button">Close</Button></DialogFooter></DialogContent></Dialog>;