import React, { useState } from 'react';
import { ChevronDown, ChevronUp, Download, FileSpreadsheet, FileText, History, Mail, XCircle } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '../../components/ui/sheet';
import { formatSectionLabels } from './misConstants';

const statusClass = (status) => status === 'sent' ? 'bg-emerald-100 text-emerald-800' : status === 'failed' ? 'bg-red-100 text-red-800' : 'bg-amber-100 text-amber-800';

export default function MISDeliveryHistory({ deliveries, onDownload }) {
  const [selected, setSelected] = useState(null); const [downloading, setDownloading] = useState(''); const [recipientsExpanded, setRecipientsExpanded] = useState(false);
  const download = async (delivery, format) => { setDownloading(`${delivery.id}-${format}`); try { await onDownload(delivery, format); } finally { setDownloading(''); } };
  return <section className="space-y-5" data-testid="mis-delivery-history"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-800">Audit trail</p><h2 className="mt-1 text-xl font-semibold text-stone-950">Delivery history</h2><p className="mt-2 text-sm text-stone-500">Generated files and configuration snapshots stay available after a schedule changes or is deleted.</p></div><div className="overflow-hidden border-y border-emerald-950/10" data-testid="mis-delivery-history-list">{deliveries.length ? deliveries.map((delivery) => <button type="button" key={delivery.id} onClick={() => { setSelected(delivery); setRecipientsExpanded(false); }} className="grid w-full gap-3 border-b border-emerald-950/10 px-1 py-5 text-left transition-colors last:border-b-0 hover:bg-emerald-50/50 md:grid-cols-[1.2fr_0.8fr_0.55fr_auto] md:items-center" data-testid={`mis-delivery-row-${delivery.id}`}><div><p className="font-semibold text-stone-950">{delivery.schedule_name}</p><p className="mt-1 text-sm text-stone-500">{new Date(delivery.generated_at).toLocaleString()}</p></div><div><p className="text-sm text-stone-700">{delivery.reporting_period_label || `${delivery.filters?.reporting_period_start} — ${delivery.filters?.reporting_period_end}`}</p><p className="mt-1 text-xs text-stone-500">{formatSectionLabels(delivery.content?.sections) || 'Full ESG report'}</p></div><div><p className="text-sm text-stone-700" data-testid={`mis-delivery-recipient-count-${delivery.id}`}>{delivery.recipients?.length || 0} recipient{delivery.recipients?.length === 1 ? '' : 's'}</p></div><span className={`justify-self-start px-2.5 py-1 text-xs font-semibold ${statusClass(delivery.status)}`} data-testid={`mis-delivery-status-${delivery.id}`}>{delivery.status}</span></button>) : <div className="px-6 py-16 text-center" data-testid="mis-delivery-history-empty"><History className="mx-auto h-8 w-8 text-emerald-800" /><p className="mt-4 font-semibold text-stone-900">No reports have been delivered yet.</p><p className="mt-2 text-sm text-stone-500">Once a scheduled or manual report is sent, delivery records will appear here.</p></div>}</div>
    <Sheet open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}>{selected && <SheetContent className="w-full overflow-y-auto bg-white sm:max-w-xl" data-testid="mis-delivery-detail-sheet"><SheetHeader><SheetTitle>{selected.schedule_name}</SheetTitle><SheetDescription>Audit details for this generated MIS delivery.</SheetDescription></SheetHeader><div className="mt-8 space-y-7 text-sm" data-testid="mis-delivery-detail-content"><Detail label="Generated" value={new Date(selected.generated_at).toLocaleString()} /><ReportingContext delivery={selected} /><Detail label="Facilities" value={selected.facility_mode === 'all' ? 'All facilities' : selected.facility_names?.join(', ')} /><Detail label="Included sections" value={formatSectionLabels(selected.content?.sections) || 'Full ESG report'} /><div><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">Recipients</p><Button variant="ghost" size="sm" onClick={() => setRecipientsExpanded((current) => !current)} data-testid="mis-delivery-recipients-toggle-button">{recipientsExpanded ? 'Hide recipients' : `View ${selected.recipients?.length || 0} recipients`}{recipientsExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</Button></div>{recipientsExpanded && <div className="mt-3 max-h-56 space-y-2 overflow-y-auto border-t border-emerald-950/10 pt-3" data-testid="mis-delivery-recipients-list">{selected.recipients?.map((recipient) => <p key={recipient.email} className="flex items-center gap-2 text-stone-800" data-testid={`mis-delivery-recipient-${selected.id}-${recipient.email}`}><Mail className="h-4 w-4 text-emerald-800" />{recipient.email}</p>)}</div>}</div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">Delivery status</p><p className={`mt-2 font-semibold ${selected.status === 'sent' ? 'text-emerald-700' : 'text-red-700'}`} data-testid="mis-delivery-detail-status">{selected.status === 'sent' ? '✓ Successfully delivered' : selected.status}</p>{selected.failure_reason && <p className="mt-2 flex gap-2 text-red-700" data-testid="mis-delivery-failure-reason"><XCircle className="h-4 w-4 shrink-0" />{selected.failure_reason}</p>}</div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">Generated file</p><div className="mt-3 flex flex-wrap gap-2">{selected.artifacts?.map((artifact) => <Button key={artifact.format} variant="outline" onClick={() => download(selected, artifact.format)} disabled={downloading === `${selected.id}-${artifact.format}`} data-testid={`mis-delivery-download-${selected.id}-${artifact.format}`}>{artifact.format === 'pdf' ? <FileText className="h-4 w-4" /> : <FileSpreadsheet className="h-4 w-4" />}{downloading === `${selected.id}-${artifact.format}` ? 'Preparing…' : `Download ${artifact.format.toUpperCase()}`}</Button>)}</div></div></div></SheetContent>}</Sheet>
  </section>;
}

function Detail({ label, value }) { return <div><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">{label}</p><p className="mt-2 text-stone-800">{value || 'Not recorded'}</p></div>; }

function ReportingContext({ delivery }) {
  const context = delivery.reporting_context;
  if (!context) return <Detail label="Reporting period" value={delivery.reporting_period_label || `${delivery.filters?.reporting_period_start} — ${delivery.filters?.reporting_period_end}`} />;
  return <div className="grid gap-4 border-y border-emerald-950/10 py-5 sm:grid-cols-2" data-testid="mis-delivery-reporting-context"><Detail label="Reporting period" value={context.reporting_period?.label} /><Detail label="Compared with" value={context.comparison_period?.label} /><Detail label="Previous year" value={context.previous_year_period?.label} /><Detail label="YTD" value={`${context.ytd_period?.start_date} – ${context.ytd_period?.end_date}`} /><Detail label="Reporting calendar" value={context.reporting_calendar?.label} />{context.reporting_period?.is_partial && <Detail label="Period status" value="Partial period — based on available records through execution date" />}</div>;
}