import React from 'react';
import { ArrowRight, CalendarClock, Mail, Send, ShieldCheck } from 'lucide-react';
import { Button } from '../../components/ui/button';

const metrics = [
  { key: 'active_schedules', label: 'Active schedules', detail: 'Reports currently scheduled', icon: CalendarClock, tone: 'text-emerald-800 bg-emerald-50' },
  { key: 'reports_delivered', label: 'Reports delivered', detail: 'Across all configurations', icon: Send, tone: 'text-blue-800 bg-blue-50' },
  { key: 'recipients', label: 'Recipients', detail: 'Across delivery history', icon: Mail, tone: 'text-amber-800 bg-amber-50' },
  { key: 'success_rate', label: 'Success rate', detail: 'Successful delivery events', icon: ShieldCheck, tone: 'text-violet-800 bg-violet-50' },
];

export default function MISOverview({ overview, onHistory }) {
  return <section className="space-y-8" data-testid="mis-overview"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4" data-testid="mis-overview-metrics">{metrics.map(({ key, label, detail, icon: Icon, tone }) => <article key={key} className="border border-emerald-950/10 bg-white p-5 shadow-sm transition-transform hover:-translate-y-0.5" data-testid={`mis-overview-card-${key}`}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">{label}</p><p className="mt-4 font-mono text-3xl font-semibold text-stone-950" data-testid={`mis-overview-value-${key}`}>{key === 'success_rate' ? `${overview?.[key] || 0}%` : overview?.[key] || 0}</p></div><span className={`flex h-9 w-9 items-center justify-center ${tone}`}><Icon className="h-4 w-4" /></span></div><p className="mt-4 text-sm text-stone-500">{detail}</p></article>)}</div>
    <div className="border-t border-emerald-950/10 pt-8" data-testid="mis-recent-deliveries"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-800">Recent activity</p><h2 className="mt-1 text-xl font-semibold text-stone-950">Recent deliveries</h2></div><Button variant="ghost" onClick={onHistory} className="text-emerald-900 hover:bg-emerald-50 hover:text-emerald-950" data-testid="mis-view-delivery-history-button">View delivery history <ArrowRight className="h-4 w-4" /></Button></div>
      <div className="mt-5 divide-y divide-emerald-950/10">{overview?.recent_deliveries?.length ? overview.recent_deliveries.map((delivery) => <article className="flex flex-col justify-between gap-2 py-4 sm:flex-row sm:items-center" key={delivery.id} data-testid={`mis-recent-delivery-${delivery.id}`}><div><p className="font-medium text-stone-950">{delivery.schedule_name}</p><p className="mt-1 text-sm text-stone-500">{new Date(delivery.generated_at).toLocaleString()} · Sent to {delivery.recipients?.length || 0} recipient{delivery.recipients?.length === 1 ? '' : 's'}</p></div><span className={`text-sm font-semibold ${delivery.status === 'sent' ? 'text-emerald-700' : 'text-amber-700'}`} data-testid={`mis-recent-delivery-status-${delivery.id}`}>{delivery.status === 'sent' ? '✓ Sent' : delivery.status}</span></article>) : <div className="py-12 text-center" data-testid="mis-recent-deliveries-empty"><p className="font-medium text-stone-800">No reports have been delivered yet.</p><p className="mt-2 text-sm text-stone-500">Once a scheduled or manual report is sent, delivery records will appear here.</p></div>}</div>
    </div></section>;
}