import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { AlertCircle, BarChart3, CheckCircle2, Clock3, FileText, Loader2, Sparkles } from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Card, CardContent } from '../../components/ui/card';
import { ModulePageHeader } from '../../components/ModulePageHeader';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

const templateIcon = { ghg_inventory: FileText, ai_executive_summary: Sparkles, emissions_summary: BarChart3, kpi_progress: BarChart3, workflow_status: CheckCircle2, evidence_readiness: AlertCircle };
const statusStyle = { ready: 'bg-emerald-50 text-emerald-800 border-emerald-200', planned: 'bg-stone-100 text-stone-700 border-stone-200', unavailable: 'bg-amber-50 text-amber-800 border-amber-200' };
const statusLabel = { ready: 'Ready', planned: 'Planned', unavailable: 'Unavailable' };

export default function MISReportsFoundation({ onConfigureReport }) {
  const { getAuthHeader } = useAuth();
  const [catalog, setCatalog] = useState(null);
  const [filters, setFilters] = useState(null);
  const [history, setHistory] = useState([]);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;
    const loadFoundation = async () => {
      try {
        const catalogResponse = await axios.get(`${API}/mis-reports/catalog`, { headers: getAuthHeader() });
        if (cancelled) return;
        setCatalog(catalogResponse.data);
        if (!catalogResponse.data.can_generate_reports) return;
        const [filterResponse, historyResponse] = await Promise.all([
          axios.get(`${API}/mis-reports/filter-schema`, { headers: getAuthHeader() }),
          axios.get(`${API}/mis-reports/history`, { headers: getAuthHeader() }),
        ]);
        if (!cancelled) {
          setFilters(filterResponse.data);
          setHistory(historyResponse.data.items || []);
        }
      } catch (loadError) {
        if (!cancelled) setError(loadError.response?.data?.detail || 'The MIS Reports workspace could not be loaded.');
      }
    };
    loadFoundation();
    return () => { cancelled = true; };
  }, [getAuthHeader]);

  if (error) return <div className="mb-8 border border-red-200 bg-red-50 p-4 text-sm text-red-800" data-testid="mis-reports-load-error">{error}</div>;
  if (!catalog) return <div className="mb-8 flex items-center gap-3 border border-stone-200 bg-white p-5 text-sm text-stone-600" data-testid="mis-reports-loading-state"><Loader2 className="h-4 w-4 animate-spin text-emerald-700" />Preparing MIS Reports workspace</div>;

  return (
    <section className="mb-10" aria-labelledby="mis-reports-heading" data-testid="mis-reports-foundation">
      <div className="mb-6">
        <ModulePageHeader title="MIS Reports" icon={BarChart3} iconClassName="border-teal-200 bg-teal-50 text-teal-700" testId="mis-reports" aside={catalog.can_generate_reports && filters && <div className="grid grid-cols-2 gap-x-8 gap-y-2 border-l-2 border-emerald-800 pl-5 text-sm" data-testid="mis-reports-defaults-summary"><span className="text-stone-500">Period format</span><span className="font-semibold text-stone-900" data-testid="mis-reports-period-format">{filters.reporting_period_format}</span><span className="text-stone-500">Active facilities</span><span className="font-semibold text-stone-900" data-testid="mis-reports-facility-count">{filters.facilities.length}</span></div>} />
      </div>
      {!catalog.can_generate_reports && <div className="mb-6 flex items-center gap-3 border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900" data-testid="mis-reports-permission-notice"><AlertCircle className="h-5 w-5 shrink-0" />MIS Reports can be configured and generated by organization administrators.</div>}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3" data-testid="mis-reports-catalog-grid">
        {catalog.templates.map((template) => {
          const Icon = templateIcon[template.id] || FileText;
          const actionable = template.available && template.status === 'ready';
          return <Card key={template.id} className="flex min-h-[228px] flex-col rounded-md border-stone-200 bg-white shadow-sm" data-testid={`mis-report-card-${template.id}`}><CardContent className="flex flex-1 flex-col p-6"><div className="mb-8 flex items-start justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-md bg-emerald-50 text-emerald-800" data-testid={`mis-report-icon-${template.id}`}><Icon className="h-5 w-5" /></div><Badge className={`border ${statusStyle[template.status] || statusStyle.planned}`} data-testid={`mis-report-status-${template.id}`}>{statusLabel[template.status] || template.status}</Badge></div><p className="text-xs font-bold uppercase tracking-[0.16em] text-stone-500" data-testid={`mis-report-category-${template.id}`}>{template.category}</p><h2 className="mt-2 text-lg font-semibold text-stone-950" data-testid={`mis-report-name-${template.id}`}>{template.name}</h2><p className="mt-2 flex-1 text-sm leading-relaxed text-stone-600" data-testid={`mis-report-description-${template.id}`}>{template.description}</p>{actionable ? <Button className="mt-6 w-full bg-emerald-900 text-white hover:bg-emerald-800" onClick={() => onConfigureReport(template.id)} data-testid={`mis-report-configure-${template.id}`}>{template.action_label}</Button> : <div className="mt-6 flex items-center gap-2 text-xs text-stone-500" data-testid={`mis-report-state-${template.id}`}><Clock3 className="h-3.5 w-3.5" />{template.status === 'planned' ? 'Included in the next V1 phase' : 'Module access is required'}</div>}</CardContent></Card>;
        })}
      </div>
      {catalog.can_generate_reports && <div className="mt-6 border-t border-stone-200 pt-5" data-testid="mis-report-history-summary"><p className="text-xs font-bold uppercase tracking-[0.16em] text-stone-500">Report history</p><p className="mt-2 text-sm text-stone-600" data-testid="mis-report-history-status">{history.length ? `${history.length} report run${history.length === 1 ? '' : 's'} recorded.` : 'No report runs have been saved yet.'}</p></div>}
    </section>
  );
}