import React, { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Clock3, FileText, MapPin, UsersRound } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import MISContentTree from './MISContentTree';
import MISRecipientsEditor from './MISRecipientsEditor';
import { frequencyLabel } from './misConstants';

const steps = [{ title: 'Report', icon: FileText }, { title: 'Content', icon: MapPin }, { title: 'Recipients', icon: UsersRound }, { title: 'Schedule', icon: Clock3 }, { title: 'Review', icon: Check }];

function FacilityContentStep({ form, onChange, facilities }) {
  const [search, setSearch] = useState(''); const displayed = facilities.filter((facility) => facility.name.toLowerCase().includes(search.toLowerCase()));
  const selectedIds = form.filters.facility_ids;
  const toggleFacility = (id) => onChange({ ...form, filters: { ...form.filters, facility_ids: selectedIds.includes(id) ? selectedIds.filter((item) => item !== id) : [...selectedIds, id] } });
  const selectedFacilities = facilities.filter((facility) => selectedIds.includes(facility.id));
  return <div className="space-y-10" data-testid="mis-wizard-content-step"><section><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-800">Facility coverage</p><h2 className="mt-1 text-xl font-semibold text-stone-950">Choose where this report looks</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => onChange({ ...form, facility_mode: 'all', filters: { ...form.filters, facility_ids: [] } })} className={`border p-4 text-left transition-colors ${form.facility_mode === 'all' ? 'border-emerald-900 bg-emerald-50' : 'border-emerald-950/15 hover:border-emerald-700'}`} data-testid="mis-facility-mode-all"><span className="font-semibold text-stone-950">All facilities</span><span className="mt-1 block text-sm text-stone-500">Keep future facilities included automatically.</span></button><button type="button" onClick={() => onChange({ ...form, facility_mode: 'specific' })} className={`border p-4 text-left transition-colors ${form.facility_mode === 'specific' ? 'border-emerald-900 bg-emerald-50' : 'border-emerald-950/15 hover:border-emerald-700'}`} data-testid="mis-facility-mode-specific"><span className="font-semibold text-stone-950">Specific facilities</span><span className="mt-1 block text-sm text-stone-500">Build a focused report audience.</span></button></div>
    {form.facility_mode === 'specific' && <div className="mt-4 border border-emerald-950/10 p-4" data-testid="mis-facility-selector"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search facilities" data-testid="mis-facility-search-input" /><div className="mt-3 flex flex-wrap gap-2">{selectedFacilities.map((facility) => <button type="button" key={facility.id} onClick={() => toggleFacility(facility.id)} className="bg-emerald-100 px-3 py-1 text-sm text-emerald-950 transition-colors hover:bg-emerald-200" data-testid={`mis-facility-chip-${facility.id}`}>{facility.name} ×</button>)}</div><button type="button" onClick={() => onChange({ ...form, filters: { ...form.filters, facility_ids: selectedIds.length === facilities.length ? [] : facilities.map((facility) => facility.id) } })} className="mt-4 text-sm font-semibold text-emerald-900 hover:text-emerald-700" data-testid="mis-facility-select-all-button">{selectedIds.length === facilities.length ? 'Clear all' : 'Select all'}</button><div className="mt-3 grid max-h-44 gap-1 overflow-y-auto">{displayed.map((facility) => <button type="button" key={facility.id} onClick={() => toggleFacility(facility.id)} className={`flex items-center justify-between px-3 py-2 text-left text-sm transition-colors ${selectedIds.includes(facility.id) ? 'bg-emerald-50 text-emerald-950' : 'hover:bg-stone-50'}`} data-testid={`mis-facility-option-${facility.id}`}><span>{facility.name}</span><span>{selectedIds.includes(facility.id) ? 'Selected' : 'Select'}</span></button>)}</div></div>}</section><MISContentTree selected={form.content.sections} onChange={(sections) => onChange({ ...form, content: { sections } })} /></div>;
}

function ScheduleStep({ form, onChange }) { return <section className="space-y-6" data-testid="mis-wizard-schedule-step"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-800">Automation</p><h2 className="mt-1 text-xl font-semibold text-stone-950">Set the delivery rhythm</h2></div><div className="grid gap-5 sm:grid-cols-2"><div><Label htmlFor="mis-frequency">Frequency</Label><Select value={form.frequency} onValueChange={(frequency) => onChange({ ...form, frequency })}><SelectTrigger id="mis-frequency" className="mt-2" data-testid="mis-frequency-select"><SelectValue /></SelectTrigger><SelectContent>{['daily', 'weekly', 'monthly', 'quarterly', 'yearly'].map((item) => <SelectItem value={item} key={item} data-testid={`mis-frequency-option-${item}`}>{frequencyLabel(item)}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="mis-run-time">Run time</Label><Input id="mis-run-time" type="time" className="mt-2" value={form.run_time} onChange={(event) => onChange({ ...form, run_time: event.target.value })} data-testid="mis-run-time-input" /></div><div><Label htmlFor="mis-run-day">Run day</Label><Input id="mis-run-day" type="number" min="1" max="31" className="mt-2" value={form.run_day || ''} onChange={(event) => onChange({ ...form, run_day: Number(event.target.value) || null })} data-testid="mis-run-day-input" /></div><div><Label htmlFor="mis-timezone">Time zone</Label><Select value={form.timezone} onValueChange={(timezone) => onChange({ ...form, timezone })}><SelectTrigger id="mis-timezone" className="mt-2" data-testid="mis-timezone-select"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="UTC" data-testid="mis-timezone-option-utc">UTC</SelectItem><SelectItem value="Asia/Kolkata" data-testid="mis-timezone-option-ist">India Standard Time</SelectItem></SelectContent></Select></div></div><div className="border-l-2 border-emerald-800 bg-emerald-50 px-4 py-3 text-sm text-emerald-950" data-testid="mis-schedule-human-summary">{frequencyLabel(form.frequency)} · Day {form.run_day || 1} · {form.run_time} {form.timezone}</div></section>; }

function ReviewStep({ form, facilities }) { const names = form.facility_mode === 'all' ? ['All facilities'] : facilities.filter((facility) => form.filters.facility_ids.includes(facility.id)).map((facility) => facility.name); return <section data-testid="mis-wizard-review-step"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-800">Final review</p><h2 className="mt-1 text-xl font-semibold text-stone-950">Ready to automate this report?</h2><div className="mt-6 space-y-5 border border-emerald-950/15 bg-[#fdfdfb] p-6 shadow-sm" data-testid="mis-wizard-review-card"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">Configuration</p><p className="mt-1 font-semibold text-stone-950">{form.name || 'Untitled report'}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">Facilities</p><p className="mt-1 text-sm text-stone-700">{names.join(' · ') || 'Select at least one facility'}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">Report content</p><p className="mt-1 text-sm text-stone-700">{form.content.sections.join(' · ') || 'No sections selected'}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">Recipients</p><p className="mt-1 text-sm text-stone-700">{form.recipients.length} recipient{form.recipients.length === 1 ? '' : 's'}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-stone-500">Schedule</p><p className="mt-1 text-sm text-stone-700">{frequencyLabel(form.frequency)} · {form.run_time} {form.timezone}</p></div></div></section>; }

export default function MISReportWizard({ initialForm, facilities, onSave, onCancel }) {
  const [form, setForm] = useState(initialForm); const [step, setStep] = useState(0); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const canAdvance = useMemo(() => !((step === 0 && !form.name.trim()) || (step === 2 && !form.recipients.length) || (step === 1 && (!form.content.sections.length || (form.facility_mode === 'specific' && !form.filters.facility_ids.length)))), [form, step]);
  const save = async () => { setSaving(true); setError(''); try { await onSave(form); } catch (saveError) { setError(saveError.response?.data?.detail || 'Unable to save this report configuration.'); } finally { setSaving(false); } };
  const content = [<section key="report" data-testid="mis-wizard-report-step"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-800">Report identity</p><h2 className="mt-1 text-xl font-semibold text-stone-950">Name this configuration for your team</h2><div className="mt-8 max-w-xl"><Label htmlFor="mis-report-name">Report configuration name</Label><Input id="mis-report-name" className="mt-2" value={form.name} placeholder="Monthly ESG Performance Report — Management" onChange={(event) => setForm({ ...form, name: event.target.value })} data-testid="mis-report-name-input" /></div></section>, <FacilityContentStep key="content" form={form} onChange={setForm} facilities={facilities} />, <MISRecipientsEditor key="recipients" recipients={form.recipients} onChange={(recipients) => setForm({ ...form, recipients })} />, <ScheduleStep key="schedule" form={form} onChange={setForm} />, <ReviewStep key="review" form={form} facilities={facilities} />][step];
  return <div className="grid min-h-[620px] border border-emerald-950/15 bg-white lg:grid-cols-[minmax(230px,0.34fr)_1fr]" data-testid="mis-report-wizard"><aside className="bg-[#f2f6f1] p-6 lg:p-8" data-testid="mis-wizard-sidebar"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-800">{initialForm.id ? 'Edit configuration' : 'New configuration'}</p><h1 className="mt-2 text-2xl font-semibold text-stone-950">Report automation</h1><ol className="mt-10 space-y-5" data-testid="mis-wizard-steps">{steps.map(({ title, icon: Icon }, index) => <li key={title}><button type="button" onClick={() => index <= step && setStep(index)} className={`flex w-full items-center gap-3 text-left ${index === step ? 'text-emerald-950' : index < step ? 'text-emerald-800' : 'text-stone-400'}`} data-testid={`mis-wizard-step-${index + 1}`}><span className={`flex h-8 w-8 items-center justify-center border text-xs font-bold ${index === step ? 'border-emerald-900 bg-emerald-900 text-white' : index < step ? 'border-emerald-700 bg-white text-emerald-800' : 'border-stone-300'}`}>{index < step ? <Check className="h-4 w-4" /> : `0${index + 1}`}</span><span><span className="block font-semibold">{title}</span><span className="mt-0.5 block text-xs">{index === step ? 'In progress' : index < step ? 'Complete' : 'Pending'}</span></span><Icon className="ml-auto h-4 w-4" /></button></li>)}</ol></aside><main className="flex min-w-0 flex-col p-6 sm:p-10" data-testid="mis-wizard-panel"><div className="flex-1">{content}</div>{error && <p className="mt-5 text-sm text-red-700" role="alert" data-testid="mis-wizard-save-error">{error}</p>}<div className="mt-10 flex flex-wrap justify-between gap-3 border-t border-emerald-950/10 pt-5"><Button type="button" variant="ghost" onClick={step === 0 ? onCancel : () => setStep(step - 1)} data-testid="mis-wizard-back-button"><ArrowLeft className="h-4 w-4" />{step === 0 ? 'Cancel' : 'Back'}</Button>{step === steps.length - 1 ? <Button type="button" disabled={saving || !canAdvance} onClick={save} className="bg-emerald-900 text-white hover:bg-emerald-800" data-testid="mis-wizard-save-button">{saving ? 'Saving…' : 'Save schedule'}<Check className="h-4 w-4" /></Button> : <Button type="button" disabled={!canAdvance} onClick={() => setStep(step + 1)} className="bg-emerald-900 text-white hover:bg-emerald-800" data-testid="mis-wizard-next-button">Continue<ArrowRight className="h-4 w-4" /></Button>}</div></main></div>;
}