import React, { useState } from 'react';
import { CalendarClock, MoreHorizontal, Pencil, Send, Trash2 } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '../../components/ui/dropdown-menu';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '../../components/ui/alert-dialog';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { formatGeneratedFor, formatSectionLabels, frequencyLabel } from './misConstants';

const details = (schedule) => `${frequencyLabel(schedule.frequency)} · ${schedule.run_time || '09:00'} ${schedule.timezone || 'UTC'}`;

export default function MISSchedules({ schedules, onCreate, onEdit, onDelete, onSend, onPreview }) {
  const [sending, setSending] = useState(null); const [deleting, setDeleting] = useState(null); const [working, setWorking] = useState(false); const [previewing, setPreviewing] = useState(null);
  const openSend = async (schedule) => { setPreviewing(schedule.id); try { const reporting_context = await onPreview(schedule); setSending({ ...schedule, reporting_context }); } catch { setSending(schedule); } finally { setPreviewing(null); } };
  const send = async () => { setWorking(true); try { await onSend(sending); setSending(null); } finally { setWorking(false); } };
  const remove = async () => { setWorking(true); try { await onDelete(deleting); setDeleting(null); } finally { setWorking(false); } };
  return <section className="space-y-5" data-testid="mis-schedules"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-800">Automation</p><h2 className="mt-1 text-xl font-semibold text-stone-950">Schedules & delivery</h2><p className="mt-2 text-sm text-stone-500">One configuration sends the right ESG view to its chosen stakeholders.</p></div><Button onClick={onCreate} className="bg-emerald-900 text-white hover:bg-emerald-800" data-testid="mis-create-schedule-button"><CalendarClock className="h-4 w-4" />Create schedule</Button></div>
    <div className="overflow-hidden border-y border-emerald-950/10" data-testid="mis-schedules-list">{schedules.length ? schedules.map((schedule) => <article key={schedule.id} className="group grid gap-4 border-b border-emerald-950/10 px-1 py-5 transition-colors last:border-b-0 hover:bg-emerald-50/50 md:grid-cols-[minmax(240px,1.5fr)_0.7fr_0.9fr_auto] md:items-center" data-testid={`mis-schedule-row-${schedule.id}`}><div><p className="font-semibold text-stone-950">{schedule.name}</p><p className="mt-1 truncate text-sm text-stone-500" data-testid={`mis-schedule-recipients-${schedule.id}`}>{(schedule.recipients?.length ? schedule.recipients.map((recipient) => recipient.email) : schedule.recipient_emails).join(', ')}</p></div><div><span className="inline-flex bg-emerald-100 px-2.5 py-1 text-xs font-semibold text-emerald-950" data-testid={`mis-schedule-frequency-${schedule.id}`}>{frequencyLabel(schedule.frequency)}</span><p className="mt-1 text-xs text-stone-500">{details(schedule)}</p></div><div><p className="text-sm font-medium text-stone-800" data-testid={`mis-schedule-next-run-${schedule.id}`}>{schedule.next_run_at ? new Date(schedule.next_run_at).toLocaleString() : 'Paused'}</p><p className={`mt-1 text-xs font-semibold ${schedule.is_enabled ? 'text-emerald-700' : 'text-stone-500'}`}>{schedule.is_enabled ? 'Active' : 'Disabled'}</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`Actions for ${schedule.name}`} data-testid={`mis-schedule-actions-${schedule.id}`}><MoreHorizontal className="h-5 w-5" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem disabled={previewing === schedule.id} onClick={() => openSend(schedule)} data-testid={`mis-schedule-send-${schedule.id}`}><Send className="mr-2 h-4 w-4" />{previewing === schedule.id ? 'Preparing…' : 'Send now'}</DropdownMenuItem><DropdownMenuItem onClick={() => onEdit(schedule)} data-testid={`mis-schedule-edit-${schedule.id}`}><Pencil className="mr-2 h-4 w-4" />Edit</DropdownMenuItem><DropdownMenuItem className="text-red-700 focus:text-red-700" onClick={() => setDeleting(schedule)} data-testid={`mis-schedule-delete-${schedule.id}`}><Trash2 className="mr-2 h-4 w-4" />Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu></article>) : <div className="px-6 py-16 text-center" data-testid="mis-schedules-empty"><CalendarClock className="mx-auto h-8 w-8 text-emerald-800" /><p className="mt-4 font-semibold text-stone-900">No report schedules yet.</p><p className="mt-2 text-sm text-stone-500">Automate your ESG management reporting by creating your first schedule.</p><Button onClick={onCreate} className="mt-5 bg-emerald-900 text-white hover:bg-emerald-800" data-testid="mis-schedules-empty-create-button">Create schedule</Button></div>}</div>
    <Dialog open={Boolean(sending)} onOpenChange={(open) => !open && setSending(null)}><DialogContent className="max-w-xl bg-white" data-testid="mis-send-now-dialog"><DialogHeader><DialogTitle>Send report now?</DialogTitle><DialogDescription>This generates the scheduled report and sends the stored artifact to every configured recipient.</DialogDescription></DialogHeader>{sending && <div className="space-y-3 border-y border-emerald-950/10 py-4 text-sm" data-testid="mis-send-now-summary"><p><span className="text-stone-500">Report </span><strong>{sending.name}</strong></p><p data-testid="mis-send-now-generated-for"><span className="text-stone-500">Generated for </span><strong>{formatGeneratedFor(sending)}</strong></p><p><span className="text-stone-500">Content </span>{formatSectionLabels(sending.content?.sections) || 'Configured ESG report'}</p><p><span className="text-stone-500">Facilities </span>{sending.facility_mode === 'all' ? 'All facilities' : `${sending.filters?.facility_ids?.length || 0} selected`}</p><p><span className="text-stone-500">Recipients </span>{(sending.recipients?.length || sending.recipient_emails?.length || 0)} · {(sending.recipients?.map((recipient) => recipient.email) || sending.recipient_emails || []).join(', ')}</p></div>}<DialogFooter><Button variant="outline" onClick={() => setSending(null)} data-testid="mis-send-now-cancel-button">Cancel</Button><Button disabled={working} onClick={send} className="bg-emerald-900 text-white hover:bg-emerald-800" data-testid="mis-send-now-confirm-button"><Send className="h-4 w-4" />{working ? 'Sending…' : 'Send now'}</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={Boolean(deleting)} onOpenChange={(open) => !open && setDeleting(null)}><AlertDialogContent data-testid="mis-delete-schedule-dialog"><AlertDialogHeader><AlertDialogTitle>Delete this schedule?</AlertDialogTitle><AlertDialogDescription>This will stop all future automated deliveries for this report. Previous delivery history will not be deleted.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel data-testid="mis-delete-schedule-cancel-button">Cancel</AlertDialogCancel><AlertDialogAction disabled={working} onClick={remove} className="bg-red-700 text-white hover:bg-red-800" data-testid="mis-delete-schedule-confirm-button">{working ? 'Deleting…' : 'Delete schedule'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
}