import React, { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { Button } from '../../../components/ui/button';
import { Checkbox } from '../../../components/ui/checkbox';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../../components/ui/dialog';
import { Input } from '../../../components/ui/input';
import { Label } from '../../../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../../components/ui/select';

const defaultRule = (responseType) => responseType === 'yes_no' ? 'boolean' : responseType === 'dropdown' ? 'choice_mapping' : responseType === 'text' ? 'manual' : 'higher_is_better';
const blankRow = () => ({ question_text: '', category: 'environment', response_type: 'yes_no', importance: 'medium', scoring_rule: 'boolean', required: true, options_text: '', option_scores: {}, yes_score: 100, no_score: 0 });
const dropdownValues = (row) => row.options_text.split(',').map((value) => value.trim()).filter(Boolean);

export const QuestionLedgerDialog = ({ open, onOpenChange, onSave, saving }) => {
  const [rows, setRows] = useState([blankRow()]);
  useEffect(() => { if (open) setRows([blankRow()]); }, [open]);
  const updateRow = (index, patch) => setRows((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  const removeRow = (index) => setRows((current) => current.length === 1 ? current : current.filter((_, rowIndex) => rowIndex !== index));
  return <Dialog open={open} onOpenChange={onOpenChange}>
    <DialogContent className="flex max-h-[calc(100dvh-2rem)] max-w-6xl flex-col gap-0 overflow-hidden bg-white p-0" data-testid="question-ledger-dialog">
      <DialogHeader className="border-b border-emerald-100 bg-emerald-50 px-6 py-5"><DialogTitle>Add questions</DialogTitle><DialogDescription>Create several supplier questions in one ledger. Configure scoring in the row where you create the question.</DialogDescription></DialogHeader>
      <div className="min-h-0 flex-1 overflow-y-auto px-6 py-5"><div className="space-y-3" data-testid="question-ledger-rows">{rows.map((row, index) => <div key={index} className="min-w-0 space-y-3 rounded-lg border border-stone-200 bg-white p-4" data-testid={`question-ledger-row-${index}`}>
        <div className="grid min-w-0 gap-3 xl:grid-cols-[minmax(15rem,1fr)_8rem_8rem_8rem_9rem_6rem_2.5rem] xl:items-center">
          <Input value={row.question_text} onChange={(event) => updateRow(index, { question_text: event.target.value })} placeholder="Question text" data-testid={`question-ledger-text-${index}`} />
          <Select value={row.category} onValueChange={(category) => updateRow(index, { category })}><SelectTrigger data-testid={`question-ledger-category-${index}`}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="environment">Environment</SelectItem><SelectItem value="social">Social</SelectItem><SelectItem value="governance">Governance</SelectItem></SelectContent></Select>
          <Select value={row.response_type} onValueChange={(response_type) => updateRow(index, { response_type, scoring_rule: defaultRule(response_type), options_text: response_type === 'dropdown' ? row.options_text : '' })}><SelectTrigger data-testid={`question-ledger-response-type-${index}`}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="yes_no">Yes / No</SelectItem><SelectItem value="numeric">Numeric</SelectItem><SelectItem value="percentage">Percentage</SelectItem><SelectItem value="text">Text</SelectItem><SelectItem value="dropdown">Dropdown</SelectItem></SelectContent></Select>
          <Select value={row.importance} onValueChange={(importance) => updateRow(index, { importance })}><SelectTrigger data-testid={`question-ledger-importance-${index}`}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="low">Low</SelectItem><SelectItem value="medium">Medium</SelectItem><SelectItem value="high">High</SelectItem><SelectItem value="critical">Critical</SelectItem></SelectContent></Select>
          <Select value={row.scoring_rule} onValueChange={(scoring_rule) => updateRow(index, { scoring_rule })}><SelectTrigger data-testid={`question-ledger-scoring-${index}`}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="boolean">Yes/No score</SelectItem><SelectItem value="higher_is_better">Higher is better</SelectItem><SelectItem value="lower_is_better">Lower is better</SelectItem><SelectItem value="target_based">Target based</SelectItem><SelectItem value="choice_mapping">Choice mapping</SelectItem><SelectItem value="manual">Manual review</SelectItem></SelectContent></Select>
          <label className="flex items-center gap-2 text-sm"><Checkbox checked={row.required} onCheckedChange={(required) => updateRow(index, { required: Boolean(required) })} data-testid={`question-ledger-required-${index}`} />Required</label><Button variant="ghost" size="icon" onClick={() => removeRow(index)} disabled={rows.length === 1} data-testid={`remove-question-ledger-row-${index}`}><Trash2 className="h-4 w-4 text-rose-600" /></Button>
        </div>
        {row.response_type === 'yes_no' && <div className="grid gap-3 rounded-md border border-emerald-100 bg-emerald-50/50 p-3 sm:grid-cols-2" data-testid={`question-ledger-yes-no-scores-${index}`}><div><Label className="text-xs">Yes score</Label><Input type="number" min="0" max="100" value={row.yes_score} onChange={(event) => updateRow(index, { yes_score: event.target.value })} data-testid={`question-ledger-yes-score-${index}`} /></div><div><Label className="text-xs">No score</Label><Input type="number" min="0" max="100" value={row.no_score} onChange={(event) => updateRow(index, { no_score: event.target.value })} data-testid={`question-ledger-no-score-${index}`} /></div></div>}
        {row.response_type === 'dropdown' && <div className="space-y-3 rounded-md border border-amber-200 bg-amber-50/50 p-3" data-testid={`question-ledger-dropdown-config-${index}`}><div><Label className="text-xs">Options</Label><Input value={row.options_text} onChange={(event) => updateRow(index, { options_text: event.target.value })} placeholder="Option A, Option B" data-testid={`question-ledger-options-${index}`} /></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{dropdownValues(row).map((value) => <div key={value}><Label className="text-xs">{value} score</Label><Input type="number" min="0" max="100" value={row.option_scores[value] ?? ''} onChange={(event) => updateRow(index, { option_scores: { ...row.option_scores, [value]: event.target.value } })} data-testid={`question-ledger-option-score-${index}-${value}`} /></div>)}</div></div>}
      </div>)}</div><Button variant="outline" size="sm" className="mt-4" onClick={() => setRows((current) => [...current, blankRow()])} data-testid="add-question-ledger-row"><Plus className="mr-1 h-4 w-4" />Add row</Button></div>
      <DialogFooter className="border-t border-stone-200 px-6 py-4"><Button variant="outline" onClick={() => onOpenChange(false)} data-testid="cancel-question-ledger">Cancel</Button><Button onClick={() => onSave(rows)} disabled={saving} data-testid="save-question-ledger">{saving ? 'Adding…' : `Add ${rows.length} question${rows.length === 1 ? '' : 's'}`}</Button></DialogFooter>
    </DialogContent>
  </Dialog>;
};